=== ga4gh-beacon/beacon-v2/models/json/beacon-v2-default-model/individuals/defaultSchema.json
{
    "$comment": "version: ga4gh-beacon-individual-v2.0.0",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "description": "Schema for an individual entry.",
    "properties": {
        "diseases": {
            "description": "List of disease(s) been diagnosed to the individual, defined by disease ontology ID(s), age of onset, stage and the presence of family history.",
            "items": {
                "$ref": "../common/disease.json"
            },
            "type": "array"
        },
        "ethnicity": {
            "$ref": "../common/commonDefinitions.json#/$defs/Ethnicity",
            "description": "Ethnic background of the individual. Value from NCIT Race (NCIT:C17049) ontology term descendants, e.g. NCIT:C126531 (Latin American). A geographic ancestral origin category that is assigned to a population group based mainly on physical characteristics that are thought to be distinct and inherent. [ NCI ] "
        },
        "exposures": {
            "items": {
                "$ref": "../common/exposure.json"
            },
            "type": "array"
        },
        "geographicOrigin": {
            "$ref": "../common/commonDefinitions.json#/$defs/GeographicLocation",
            "description": "Individual's country or region of origin (birthplace or residence place regardless of ethnic origin). Value from GAZ Geographic Location ontology (GAZ:00000448), e.g. GAZ:00002459 (United States of America)."
        },
        "id": {
            "description": "Individual identifier (internal ID).",
            "example": "P0001",
            "type": "string"
        },
        "info": {
            "$ref": "../common/info.json"
        },
        "interventionsOrProcedures": {
            "items": {
                "$ref": "../common/procedure.json"
            },
            "type": "array"
        },
        "karyotypicSex": {
            "$ref": "../common/commonDefinitions.json#/$defs/KaryotypicSex",
            "description": "The chromosomal sex of an individual represented from a selection of options."
        },
        "measures": {
            "items": {
                "$ref": "../common/measurement.json"
            },
            "type": "array"
        },
        "pedigrees": {
            "items": {
                "$ref": "../common/pedigree.json"
            },
            "type": "array"
        },
        "phenotypicFeatures": {
            "items": {
                "$ref": "../common/phenotypicFeature.json"
            },
            "type": "array"
        },
        "sex": {
            "$ref": "../common/commonDefinitions.json#/$defs/Sex",
            "description": "Sex of the individual. Value from NCIT General Qualifier `NCIT:C27993`:    * `unknown`: not assessed or not availablel `NCIT:C17998` * `female`: `NCIT:C16576` * `male`: `NCIT:C20197`"
        },
        "treatments": {
            "items": {
                "$ref": "../common/treatment.json"
            },
            "type": "array"
        }
    },
    "required": [
        "id",
        "sex"
    ],
    "title": "Individual",
    "type": "object"
}

=== ga4gh-beacon/beacon-v2/models/json/beacon-v2-default-model/individuals/examples/individual-with-pedigree-MID-example.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "diseases": [
        {
            "familyHistory": true,
            "onset": {
                "ageGroup": {
                    "id": "NCIT:C16731",
                    "label": "Newborn"
                }
            },
            "severity": {
                "id": "HP:0012828",
                "label": "Severe"
            },
            "term": {
                "id": "HP:0001645",
                "label": "Sudden cardiac death"
            }
        }
    ],
    "ethnicity": {
        "id": "NCIT:C43851",
        "label": "European"
    },
    "geographicOrigin": {
        "id": "GAZ:00002586",
        "label": "State of Wisconsin"
    },
    "id": "Ind001",
    "pedigrees": [
        {
            "disease": {
                "term": {
                    "id": "HP:0001645",
                    "label": "Sudden cardiac death"
                }
            },
            "id": "SCD-Pedigree001",
            "members": [
                {
                    "affected": true,
                    "memberId": "Ind001",
                    "role": {
                        "id": "NCIT:C64435",
                        "label": "Proband"
                    }
                },
                {
                    "affected": false,
                    "memberId": "Ind011",
                    "role": {
                        "id": "NCIT:C96572",
                        "label": "Biological Father"
                    }
                },
                {
                    "affected": false,
                    "memberId": "Ind012",
                    "role": {
                        "id": "NCIT:C96572",
                        "label": "Biological Father"
                    }
                },
                {
                    "affected": false,
                    "memberId": "Ind022",
                    "role": {
                        "id": "NCIT:C111201",
                        "label": "Full Brother"
                    }
                }
            ],
            "numSubjects": 4
        }
    ],
    "sex": {
        "id": "NCIT:C16576",
        "label": "female"
    }
}
